### ISSUE TITLE
Modal de inicio... buscando

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#44]
Como modal/servicio (ver Modal de ionic por las dudas) crear la página de inicio que en principio cargaría el slider principal. Y en general sirve como medio antes de realizar la carga: https://marvelapp.com/4h098b8/screen/68074281, ésta es de muestra, ya hay una en diseño, simplemente dejar con color de fondo hasta que tengamos el defiinitivo.
Habría que definir las transiciones en general del sitio y en particular de la página de búsqueda a las otras.

**Comment by brunosarlo** [comment]
La implementación final fue centralizada en la página de mapa, donde esta el slider de inicio también, no en un modal sino como componente.

El slider del inicio quedó 100%, también slider implementado en página de Consejos.

Quedó la funcionalidad "loading" con un "splash screen" con fondo pleno y logo.

Las transiciones de páginas se implementaron con animaciones de Ionic5 en un componente animations. Aún hay problemas complejos para resolver transiciones complejas entre todas las páginas sobre todo entre tabs y páginas externas. Una opción es en esos casos usar el "splash screen". Las transiciones hechas fueron del cabezal de pagina padre a hijos.

**Comment by fernandouval** [comment]
El splash/modal no se muestra al comienzo de la carga de la aplicación.
