### ISSUE TITLE
Buscador

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#45]
Conectar buscador con backend. Según la maqueta los resultados de la búsqueda cuentan con un nombre y un método de deposición. Hay que considerar que la estructura que estamos utilizando es de productos-residuos-materiales, por lo que creo que es importante establecer la distinción de alguna forma en los resultados. 
Además posicionar el buscador y ofrecer los resultados según la maqueta.

**Comment by danielcarranza** [comment]
Creo que para el usuario debería ser indistinto buscar cualquiera de los tres niveles.
Supongamos tres ejemplos que tengan relación entre sí; Plástico-Botella PET-Botella de Coca Cola 500cc.

Si busco "Plástico", no me va a poner el texto de forma de disposición, porque no hay una universal para el material. Me muestra todos los contenedores de planes que aceptan plástico.

Si busco "Botella PET", me pone el texto de forma de disposición y me muestra todos los contenedores de planes que aceptan plástico.

Si busco "Botella de Coca Cola 500cc" me pone el texto de forma de disposición del residuo al que está asociado el producto (Botella PET). Me muestra todos los contenedores de planes que aceptan plástico.

Creo que para el usuario no es importante mostrarle a qué nivel busca, lo importante es que busque lo que busque, obtenga los contenedores que lo aceptan y la información que tengamos de cómo disponer los residuos.
¿Te cierra?

**Comment by fernandouval** [comment]
Vienen 4 campos del back:
1. Id
2. Tipo
3. Deposición
4. ID Material
En selección, envía:
1. ID
2. Tipo
El back devuelve los contenedores asociados ordenados por proximidad.

**Comment by brunosarlo** [comment]
Quedó implementado el componente "ionic4-auto-complete", estilos de resultados y sugerencias y transiciones. Faltan detalles y algo de conexión con backend.

**Comment by fernandouval** [comment]
Falta dar estilo a los resultados, falta también las asociaciones correspondientes del lado del back.

**Comment by danielcarranza** [comment]
Capaz estoy entendiendo mal, ¿falta hacer o definir? El estilo sería éste: https://app.zeplin.io/project/58f7a283fff0de5abc764f53/screen/5ea6e94e7b8f7726d32edf1a/
Y de hecho entiendo que ya empezaste a aplicarlo.

No estoy seguro porqué estoy asignado.

**Comment by danielcarranza** [comment]
Está resuelta llamada pregunta, ¿no? ¿Saco el tag?

**Comment by danielcarranza** [comment]
Revisar estilo de las búsquedas sugeridas

**Comment by fernandouval** [comment]
1- El estilo de las búsquedas estaría. Hay un tema con el pasaje a desktop que como no está definido el comportamiento quedó en que las predefinidas tienen un largo de 200px mínimo y se van acomodando en línea a medida que van entrando por la resolución de la pantalla. Para los resultados de búsqueda como es 1 por línea se limitó el largo a 380px, porque al 100% en resoluciones grandes queda horrible.  
2- Estuve evaluando también el comportamiento de la búsqueda ya que puede pasar que no hayan contendores donde se está viendo, por lo que la búsqueda es mejor realizarla por proximidad. Lo orto que puede pasar es que los parámetros de proximidad no devuelvan resultados. Por esta razón había pensado que sería bueno poner un límite de 300km y devolver no más de 10 contenedores en base a la proximidad al usuario (¿o al centro del mapa al momento de realizar la búsqueda en caso que no esté localizado?) me parece que la solución tiene que ir por ahí. Hay que tener en cuenta que la vista iría centrada en los resultados estos (por lo que capaz es mejor devolver menos contenedores (o lo podemos centrar en menos, pero dejaría de tener sentido levantar más).  
3- Lo otro es el comportamiento una vez que el usuario selecciona el material, asumo que ahí todas las actualizaciones de pines que se hagan se hacen en base al material hasta que lo saque haciendo click en la cruz del resultado de búsqueda que se muestra en el mapa?

**Comment by danielcarranza** [comment]
1 - Tendría que verlo para confirmar que entiendo todo, pero suena bien lo de 380 más. uno por línea. Las sugeridas como están la verdad no me molestan para nada.

2 - Está muy bien, lógica similar a Elijo Estudiar. Simplificando, sería, siempre te muestro los 5 contenedores más cercanos de lo que estás buscando. ¿Correcto?

3 - ¡Si, exacto! Actúa como un filtro.
