### ISSUE TITLE
Maquetar Splash/Waiting

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#49]

**Comment by brunosarlo** [comment]
Hicimos un custom loading manejado desde el servicio sessions.

**Comment by fernandouval** [comment]
No se agregó el gif realizado para esta pantalla.

**Comment by fernandouval** [comment]
@danielcarranza tenemos la imagen pronta para agregar? Hay que ajustarla en el alto porque en desktop queda mal...

**Comment by danielcarranza** [comment]
No la había subido a Zeplin, mal yo.
https://app.zeplin.io/project/58f7a283fff0de5abc764f53/styleguide/components?coid=5f104865474c068c7a3d147b

¿De qué tamaño se necesita? La ajusto en un toque.

**Comment by danielcarranza** [comment]
Subí SVG nuevo, en local lo veo bien.
