### ISSUE TITLE
Detalle de contenedor

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#51]
El detalle del contenedor deberá contener los siguientes elementos (según https://marvelapp.com/4h098b8/screen/68074278):

- Programa
- Typo de contenedor
- Emplazamiento
- Dirección
- Horario (con aprox.?)
- Recibe/No recibe

Cosas que habría que revisar
1. Recibe/No recibe. Hay un problema con respecto a los datos y el diseño (atento @danielcarranza)
  - Según los datos que tenemos de la versión anterior los mismos refieren en la nueva estructura tanto a Materiales (ej: Materiales reciclables) como a Residuos (CPU, etc.).
  - Anivel de diseño se realizó la maqueta con Residuos, pero si traducimos los campos de Materiales reciclables o mismo los sub-programas de Antel Integra o Uruguay clasifica, la lista es super extensa, por lo que habría que evaluar eso.
2. Horario (con aprox.?)
  - Se puede pensar en tener un botón de hacer flexible, aún no hay interfaz pensada, la solución que se adoptó consiste en un contenido asociado al contenedor con: día, hora inicio, hora fin. Esto sin restricciones.

**Comment by danielcarranza** [comment]
Bien que te avivaste lo de "no recibe", estuve revisando la estructura vieja yo también. Creo que tenemos dos opciones:

1 - En el "Programa" está el "no recibe" que es texto. Podemos mostrar ese, aunque no quede tan lindo.

2 - Permitir seleccionar materiales o residuos sería ideal. No entendí bien lo que decías de la lista extensa... Creo que a nivel de interfaz definitivamente no puede ser una selección tipo checkboxes, más bien tendrías que buscar y agregar.

Y no entendí bien lo del horario flexible, perdón.

**Comment by danielcarranza** [comment]
Está resuelta llamada pregunta, ¿no? ¿Saco el tag?

**Comment by fernandouval** [comment]
La lógica que se sigue es la siguiente. Se asociaron materiales y residuos a los subprogramas (de los cuales hereda el contenedor). Si el contenedor tiene materiales se muestran sólo estos, sino se muestran los residuos. Para el caso de las cosas que no reciben se mustra sólo texto y en recibe texto (en caso de tener) e íconos...
