### ISSUE TITLE
Carga inicial de datos

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#58]
¿Cómo vamos a manejar los tipos de contenedores? Pensando más bien en la imagen habría que definir si los íconos van a vivir en el back (y mandamos la URL) o si van en la app y nos manejamos por código. O en modalidad mixta y cargarlos al comienzo. En la primera ganamos libertad perdemos velocidad y en la segunda perdemos flexibilidad (sólo actualizando la app podemos agregar contenedores, pero quizás sea lo mejor) y ganamos velocidad.

**Comment by danielcarranza** [comment]
En el esquema de datos y wireframes de admin está pensado como algo que se maneja desde el back. Por más que no se agregan contenedores todos los días, creo que es MUY importante para hacer la herramienta más replicable en otros países. Y aún limitándose a la experiencia en Uruguay, los contenedores cambian (ej. en Canelones) y hoy por hoy no lo logramos reflejar.
