### ISSUE TITLE
Ocultar indicaciones en ruta a contenedor

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#62]
O bien que no se muestren las indicaciones de las rutas o lo hagan minimizadas?

**Comment by danielcarranza** [comment]
Me parece que en 99% de los casos las indicaciones son flor de overkill. Con la ruta basta.

Ni ahí me parece importante pero si REALMENTE quisiéramos dar indicaciones útiles, yo me inclinaría más bien por tener un botón de "Direcciones", que vía llamada te abra tu app de mapas predeterminada. Nadie va a estar mirando DR todo el camino en un auto, ponele. Que te lleve a lo que uses, Maps, Waze, lo que sea y chau. Pero insisto, me parece un poco mucho en principio.

**Comment by brunosarlo** [comment]
Oculte el "itinerario" como le llaman. Igual mustra algo aún. 

Lo oculte desde los estilos: .leaflet-routing-container
Y desde las opciones: show: false
