### ISSUE TITLE
Guardar cookie para no mostrar el slider y ocultar slider cuando no quedan más slides

### ISSUE THREAD

**Issue by fernandouval** [datauy/DondeReciclo-3#63]
Siempre que se pone skip no se muestra más o se le va a preguntar al usuario o sólo si ve todas las slides?

**Comment by danielcarranza** [comment]
Para mí skip es idéntico a "ya lo vio".
Si lo estoy salteando porque no me molesta o no me interesa y se lo vuelvo a mostrar cada vez que entra nos va a odiar :)

Y siempre tenemos el plan B para verlo de nuevo desde el menú que hablamos.
