### ISSUE TITLE
Novedades - Novedad carga sin ocupar todo el ancho (?)

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DondeReciclo-3#87]
![image](https://user-images.githubusercontent.com/1755382/87257758-0f4a4f00-c474-11ea-82f5-ace426d0f4d2.png)

**Comment by fernandouval** [comment]
Ésto ya estaría o se sigue viendo así @danielcarranza ?

**Comment by danielcarranza** [comment]
Si, pero hay algo raro. Aparece así, pero al hacer click y entrar a la novedad se acomoda y ya queda bien cuando volvéis. Va captura. Y aclaro que no es de iOS, capturé así porque ya estaba y era más chico el video, me pasa en cualquier resolución.
[Grabación de pantalla 2020-07-16 a la(s) 09.23.50.zip](https://github.com/datauy/DondeReciclo-3/files/4931448/Grabacion.de.pantalla.2020-07-16.a.la.s.09.23.50.zip)
