### ISSUE TITLE
Novedades (leyendo una novedad) - Más alto para imagen, llegar al 100% del ancho y hacer zoom para no dejar negro a los lados.

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DondeReciclo-3#88]
![image](https://user-images.githubusercontent.com/1755382/87257807-8d0e5a80-c474-11ea-9306-be02cde58c63.png)

**Comment by fernandouval** [comment]
Está corregido el tema de la imagen como en el resto, creo que podríamos hacer lo mismo que con el resto con respecto al alto de la imágen de hacerlo variable con respecto al ancho de la pantalla, avisame si te cierra @danielcarranza

**Comment by danielcarranza** [comment]
Si, me parece perfecto y quedaría aún mejor.
Pero permite decir que quedó ESPECTACULAR.
