### ISSUE TITLE
General - ¿Mostrar menú inferior en secciones?

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DondeReciclo-3#92]
Resolvimos dejar botón "volver" en las secciones del menú superior.

**Comment by fernandouval** [comment]
Esto propondría ponerlo como un banner de links que dirijan a la página y no cambiar el funcionamiento de las tabs. Ya hice pruebas y las tabs se superponen al contenido y quedan como dos secciones mezcladas...

**Comment by danielcarranza** [comment]
Ok a no cambiar funcionamiento de las tabs.
Para no crear otra forma de navegación, yo propondría poner el mismo botón de volver que en las novedades entonces.
